name: BanningHammer
main: com.github.hatixon.banninghammer.BanningHammer
version: 0.2

commands:
  bh:
    description: Turns BanningHammer on and off!
    permission: bh.admin
  confuse:
    description: Warps a players screen!
    permission: bh.admin
    
permissions:
  bh.admin:
    default: op