name: BanningHammer
main: com.github.hatixon.banninghammer.BanningHammer
version: 0.3

commands:
  bh:
    description: /bh toggle to turn features on ad off
    permission: bh
  confuse:
    description: Warps a players screen!
    permission: bh.confuse
    
permissions:
  bh.confuse:
    default: op
  bh.toggle:
    default: op
  bh.change:
    default: op